---
title: "Class-2019-03-14"
author: "Alistair Gluck"
date: "3/14/2019"
output: html_document
---
```{r setup, include=FALSE}
# Let's all work on Spain.

# Read in the data automatically rather than rely on the download.

# Only want to use polling data from firms with at least 40 polls.

# Only want last year.

# Only 5 parties.


knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(devtools)
x <- read_csv("https://pollofpolls.eu/get/polls/ES-parliament/format/csv")
```

```{r polling}
# Make a list of firms with at least 40 polls

good_firms <- x %>% 
  group_by(firm) %>% 
  summarize(number = n()) %>% 
  ungroup() %>% 
  filter(number >= 40) %>% 
  pull(firm)
  
# Figure out date a year ago
  
# Filter out data that we want to use and send it to the plot.

x %>% 
  filter(firm %in% good_firms) %>% 
  select(-n, -source, -sd, -firm) %>% 
  filter(date > Sys.Date() - 365) %>%
  gather(key = "party", value = "poll", PP:PDeCAT) %>% 
  filter(party %in% c("PSOE", "PP", "Cs", "Podemos", "VOX")) %>% 
  filter(poll != "NA") %>%
  group_by(party) %>% 
  ggplot(aes(x = date, y = poll, color = party)) + 
  geom_smooth(se = FALSE, show.legend = FALSE) + 
  geom_point(se = FALSE, show.legend = FALSE)
  
```